# Generated by Django 5.1.5 on 2026-01-30 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=64, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_levels', to='localities.localitylevel')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='localities.locality')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='localities.localitylevel')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['level', 'parent'], name='localities__level_i_09262e_idx')],
                'unique_together': {('name', 'level', 'parent')},
            },
        ),
    ]
