# Generated by Django 5.1.5 on 2026-01-30 14:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('localities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('room', 'Room/Chumba'), ('house', 'House/Nyumba'), ('apartment', 'Apartment/Fleti'), ('shop', 'Shop/Duka'), ('office', 'Office/Ofisi'), ('warehouse', 'Warehouse/Godown'), ('land', 'Land/Kiwanja'), ('commercial', 'Commercial Building')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monthly rent in TZS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('available_rooms', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('listed_date', models.DateField(auto_now_add=True)),
                ('rules_terms', models.TextField(blank=True, help_text='Property rules and terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='localities.locality')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.owner')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-listed_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(choices=[('water_24h', '24/7 Water Supply'), ('water_tank', 'Water Tank'), ('borehole', 'Borehole'), ('electricity', 'TANESCO Electricity'), ('solar', 'Solar Power'), ('generator', 'Generator Backup'), ('security_guard', 'Security Guard/Mlinzi'), ('cctv', 'CCTV Cameras'), ('parking', 'Parking Space'), ('fence', 'Fenced Compound'), ('toilet_inside', 'Inside Toilet'), ('toilet_outside', 'Outside Toilet'), ('kitchen_inside', 'Inside Kitchen'), ('kitchen_outside', 'Outside Kitchen'), ('furnished', 'Furnished'), ('tiles', 'Tiled Floor'), ('ceiling', 'Ceiling'), ('balcony', 'Balcony'), ('garden', 'Garden'), ('wifi', 'WiFi Available')], max_length=30)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Property Amenities',
                'unique_together': {('property', 'amenity')},
            },
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('single_room', 'Single Room/Chumba Kimoja'), ('double_room', 'Double Room/Vyumba Viwili'), ('bedsitter', 'Bedsitter'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('shop_unit', 'Shop Unit'), ('office_unit', 'Office Unit'), ('warehouse_unit', 'Warehouse Unit')], max_length=20)),
                ('unit_number', models.CharField(max_length=20)),
                ('unit_rent', models.DecimalField(decimal_places=2, help_text='Monthly rent for this unit in TZS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square meters', max_digits=8, null=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('unit_features', models.TextField(blank=True, help_text='Specific features of this unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'unit_number'],
                'unique_together': {('property', 'unit_number')},
            },
        ),
    ]
