# Generated by Django 5.1.5 on 2026-01-30 14:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('leases', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('tenant_to_property', 'Tenant reviewing Property'), ('owner_to_tenant', 'Owner reviewing Tenant')], max_length=30)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('lease', models.ForeignKey(help_text='Verified lease for this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='leases.leaseagreement')),
                ('property', models.ForeignKey(blank=True, help_text='For tenant reviewing property', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property')),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_responses', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='For owner reviewing tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
    ]
