# Generated by Django 5.1.5 on 2026-01-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('plumbing', 'Plumbing/Mabomba'), ('electrical', 'Electrical/Umeme'), ('structural', 'Structural/Ujenzi'), ('appliance', 'Appliance/Vifaa'), ('pest', 'Pest Control/Wadudu'), ('cleaning', 'Cleaning/Usafi'), ('security', 'Security/Usalama'), ('water', 'Water Supply/Maji'), ('toilet', 'Toilet/Choo'), ('roof', 'Roof/Paa'), ('door_window', 'Door/Window'), ('painting', 'Painting/Rangi'), ('other', 'Other/Nyingine')], max_length=20)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low/Kawaida'), ('medium', 'Medium/Wastani'), ('high', 'High/Haraka'), ('urgent', 'Urgent/Dharura')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Repair cost in TZS', max_digits=12, null=True)),
                ('cost_responsibility', models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner'), ('shared', 'Shared')], default='owner', max_length=20)),
                ('technician_name', models.CharField(blank=True, max_length=200)),
                ('technician_contact', models.CharField(blank=True, max_length=15)),
                ('resolution_notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='accounts.owner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='accounts.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='properties.rentalunit')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance_images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.maintenancerequest')),
            ],
        ),
    ]
