# Generated by Django 5.1.5 on 2026-01-30 14:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Agreed monthly rent in TZS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('security_deposit', models.DecimalField(decimal_places=2, help_text='Security deposit in TZS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('biannual', 'Bi-Annual (6 months)'), ('annual', 'Annual (12 months)')], default='monthly', max_length=20)),
                ('payment_due_day', models.PositiveIntegerField(default=1, help_text='Day of month rent is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('terms_conditions', models.TextField(blank=True, help_text='Additional terms and conditions')),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='lease_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signature'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='draft', max_length=20)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='accounts.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.rentalunit')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
