# Generated by Django 5.1.5 on 2026-01-30 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('rent_reminder_7', 'Rent Reminder (7 days)'), ('rent_reminder_3', 'Rent Reminder (3 days)'), ('rent_due', 'Rent Due Today'), ('rent_overdue', 'Rent Overdue'), ('payment_received', 'Payment Received'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('lease_expiring', 'Lease Expiring'), ('lease_renewed', 'Lease Renewed'), ('lease_created', 'Lease Created'), ('maintenance_submitted', 'Maintenance Request Submitted'), ('maintenance_acknowledged', 'Maintenance Acknowledged'), ('maintenance_in_progress', 'Maintenance In Progress'), ('maintenance_completed', 'Maintenance Completed'), ('new_review', 'New Review'), ('review_response', 'Review Response'), ('document_verified', 'Document Verified'), ('account_verified', 'Account Verified'), ('general', 'General Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_swahili', models.TextField(blank=True, help_text='Swahili translation')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
